[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.17"
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
